name: Update Views Badge

on:
  schedule:
    - cron: '0 0 * * *' # Ejecutar diariamente a medianoche
  workflow_dispatch:

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Traffic Data
        id: traffic
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               https://api.github.com/repos/BrandonSepulveda/ToolboxBS/traffic/views > views.json

          VIEWS=$(jq '.count' views.json)

          echo "::set-output name=views::$VIEWS"

      - name: Update README with Badge
        run: |
          VIEWS=${{ steps.traffic.outputs.views }}

          sed -i "s/badge\/Views-[0-9]*/badge\/Views-${VIEWS}/g" README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'Update views badge'
          git push
